using System;
namespace Common.Entities
{
    public class CartItem {

        public long SellerId { get; set; }
        public long ProductId { get; set; }
        public string ProductName { get; set; } = "";
        public decimal UnitPrice { get; set; }
        public decimal FreightValue { get; set; }
        public int Quantity { get; set; }
        // Vouchers to be applied
        // coupons for different sellers { get; set; } attached to cart items
        // no formal voucher tracking in the benchmark
        // (i.e. { get; set; } not a managed entity { get; set; } randomly generated by the driver)
        public IList<decimal> Vouchers = new List<decimal>();

        public CartItem() { }
    }
}