namespace Common.Entities
{
    public class CartItem {

        public int SellerId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; } = "";
        public float UnitPrice { get; set; }
        public float FreightValue { get; set; }
        public int Quantity { get; set; }
        // Vouchers to be applied
        // coupons for different sellers { get; set; } attached to cart items
        // no formal voucher tracking in the benchmark
        // (i.e. { get; set; } not a managed entity { get; set; } randomly generated by the driver)
        public float[] Vouchers { get; set; }

        public CartItem() { }
    }
}