using System;
namespace Common.Entities
{
     public record CartItem
     (
        long SellerId,
        long ProductId,
        string ProductName,
        decimal UnitPrice,
        decimal FreightValue,
        int Quantity,
        // Vouchers to be applied
        // coupons for different sellers, attached to cart items
        // no formal voucher tracking in the benchmark
        // (i.e., not a managed entity, randomly generated by the driver)
        decimal[] Vouchers
     );
}