apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    retries:
      pubsubRetry:
        policy: exponential
        duration: 1s
        maxRetries: 3
  targets:
    components:
      pubsub:
        inbound:
          retry: pubsubRetry
