// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMS.Infra;

#nullable disable

namespace StockMS.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20230811173745_StockMigration")]
    partial class StockMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("stock")
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockMS.Models.StockItemModel", b =>
                {
                    b.Property<int>("seller_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("data")
                        .HasColumnType("text");

                    b.Property<int>("order_count")
                        .HasColumnType("integer");

                    b.Property<int>("qty_available")
                        .HasColumnType("integer");

                    b.Property<int>("qty_reserved")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("version")
                        .HasColumnType("integer");

                    b.Property<int>("ytd")
                        .HasColumnType("integer");

                    b.HasKey("seller_id", "product_id");

                    b.ToTable("stock_items", "stock", t =>
                        {
                            t.HasCheckConstraint("CK_StockItem_QtyAvailable", "qty_available >= 0");

                            t.HasCheckConstraint("CK_StockItem_QtyReserved", "qty_reserved >= 0");

                            t.HasCheckConstraint("CK_StockItem_QtyReservedLessThanQtyAvailable", "qty_reserved <= qty_available");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
